 const food=[
    {
      "idMeal": "52768",
      "strMeal": "Apple Frangipan Tart",
      "strDrinkAlternate": null,
      "strCategory": "Vegetarian",
      "strArea": "British",
      "strInstructions": "Preheat the oven to 200C/180C Fan/Gas 6.\r\nPut the biscuits in a large re-sealable freezer bag and bash with a rolling pin into fine crumbs. Melt the butter in a small pan, then add the biscuit crumbs and stir until coated with butter. Tip into the tart tin and, using the back of a spoon, press over the base and sides of the tin to give an even layer. Chill in the fridge while you make the filling.\r\nCream together the butter and sugar until light and fluffy. You can do this in a food processor if you have one. Process for 2-3 minutes. Mix in the eggs, then add the ground almonds and almond extract and blend until well combined.\r\nPeel the apples, and cut thin slices of apple. Do this at the last minute to prevent the apple going brown. Arrange the slices over the biscuit base. Spread the frangipane filling evenly on top. Level the surface and sprinkle with the flaked almonds.\r\nBake for 20-25 minutes until golden-brown and set.\r\nRemove from the oven and leave to cool for 15 minutes. Remove the sides of the tin. An easy way to do this is to stand the tin on a can of beans and push down gently on the edges of the tin.\r\nTransfer the tart, with the tin base attached, to a serving plate. Serve warm with cream, crème fraiche or ice cream.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/wxywrq1468235067.jpg",
      "strTags": "Tart,Baking,Fruity",
      "strYoutube": "https://www.youtube.com/watch?v=rp8Slv4INLk",
      "strIngredient1": "digestive biscuits",
      "strIngredient2": "butter",
      "strIngredient3": "Bramley apples",
      "strIngredient4": "butter, softened",
      "strIngredient5": "caster sugar",
      "strIngredient6": "free-range eggs, beaten",
      "strIngredient7": "ground almonds",
      "strIngredient8": "almond extract",
      "strIngredient9": "flaked almonds",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": null,
      "strIngredient17": null,
      "strIngredient18": null,
      "strIngredient19": null,
      "strIngredient20": null,
      "strMeasure1": "175g/6oz",
      "strMeasure2": "75g/3oz",
      "strMeasure3": "200g/7oz",
      "strMeasure4": "75g/3oz",
      "strMeasure5": "75g/3oz",
      "strMeasure6": "2",
      "strMeasure7": "75g/3oz",
      "strMeasure8": "1 tsp",
      "strMeasure9": "50g/1¾oz",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": null,
      "strMeasure17": null,
      "strMeasure18": null,
      "strMeasure19": null,
      "strMeasure20": null,
      "strSource": null,
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52893",
      "strMeal": "Apple & Blackberry Crumble",
      "strDrinkAlternate": null,
      "strCategory": "Vegetarian",
      "strArea": "British",
      "strInstructions": "Heat oven to 190C/170C fan/gas 5. Tip the flour and sugar into a large bowl. Add the butter, then rub into the flour using your fingertips to make a light breadcrumb texture. Do not overwork it or the crumble will become heavy. Sprinkle the mixture evenly over a baking sheet and bake for 15 mins or until lightly coloured.\r\nMeanwhile, for the compote, peel, core and cut the apples into 2cm dice. Put the butter and sugar in a medium saucepan and melt together over a medium heat. Cook for 3 mins until the mixture turns to a light caramel. Stir in the apples and cook for 3 mins. Add the blackberries and cinnamon, and cook for 3 mins more. Cover, remove from the heat, then leave for 2-3 mins to continue cooking in the warmth of the pan.\r\nTo serve, spoon the warm fruit into an ovenproof gratin dish, top with the crumble mix, then reheat in the oven for 5-10 mins. Serve with vanilla ice cream.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/xvsurr1511719182.jpg",
      "strTags": "Pudding",
      "strYoutube": "https://www.youtube.com/watch?v=4vhcOwVBDO4",
      "strIngredient1": "Plain Flour",
      "strIngredient2": "Caster Sugar",
      "strIngredient3": "Butter",
      "strIngredient4": "Braeburn Apples",
      "strIngredient5": "Butter",
      "strIngredient6": "Demerara Sugar",
      "strIngredient7": "Blackberrys",
      "strIngredient8": "Cinnamon",
      "strIngredient9": "Ice Cream",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "120g",
      "strMeasure2": "60g",
      "strMeasure3": "60g",
      "strMeasure4": "300g",
      "strMeasure5": "30g",
      "strMeasure6": "30g",
      "strMeasure7": "120g",
      "strMeasure8": "¼ teaspoon",
      "strMeasure9": "to serve",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://www.bbcgoodfood.com/recipes/778642/apple-and-blackberry-crumble",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53049",
      "strMeal": "Apam balik",
      "strDrinkAlternate": null,
      "strCategory": "Eggetarian",
      "strArea": "Malaysian",
      "strInstructions": "Mix milk, oil and egg together. Sift flour, baking powder and salt into the mixture. Stir well until all ingredients are combined evenly.\r\n\r\nSpread some batter onto the pan. Spread a thin layer of batter to the side of the pan. Cover the pan for 30-60 seconds until small air bubbles appear.\r\n\r\nAdd butter, cream corn, crushed peanuts and sugar onto the pancake. Fold the pancake into half once the bottom surface is browned.\r\n\r\nCut into wedges and best eaten when it is warm.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/adxcbq1619787919.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=6R8ffRRJcrg",
      "strIngredient1": "Milk",
      "strIngredient2": "Oil",
      "strIngredient3": "Eggs",
      "strIngredient4": "Flour",
      "strIngredient5": "Baking Powder",
      "strIngredient6": "Salt",
      "strIngredient7": "Unsalted Butter",
      "strIngredient8": "Sugar",
      "strIngredient9": "Peanut Butter",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "200ml",
      "strMeasure2": "60ml",
      "strMeasure3": "2",
      "strMeasure4": "1600g",
      "strMeasure5": "3 tsp",
      "strMeasure6": "1/2 tsp",
      "strMeasure7": "25g",
      "strMeasure8": "45g",
      "strMeasure9": "3 tbs",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.nyonyacooking.com/recipes/apam-balik~SJ5WuvsDf9WQ",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53050",
      "strMeal": "Ayam Percik",
      "strDrinkAlternate": null,
      "strCategory": "Nonvegetarian",
      "strArea": "Malaysian",
      "strInstructions": "In a blender, add the ingredients for the spice paste and blend until smooth.\r\nOver medium heat, pour the spice paste in a skillet or pan and fry for 10 minutes until fragrant. Add water or oil 1 tablespoon at a time if the paste becomes too dry. Don't burn the paste. Lower the fire slightly if needed.\r\nAdd the cloves, cardamom, tamarind pulp, coconut milk, water, sugar and salt. Turn the heat up and bring the mixture to boil. Turn the heat to medium low and simmer for 10 minutes. Stir occasionally. It will reduce slightly. This is the marinade/sauce, so taste and adjust seasoning if necessary. Don't worry if it's slightly bitter. It will go away when roasting.\r\nWhen the marinade/sauce has cooled, pour everything over the chicken and marinate overnight to two days.\r\nPreheat the oven to 425 F.\r\nRemove the chicken from the marinade. Spoon the marinade onto a greased (or aluminum lined) baking sheet. Lay the chicken on top of the sauce (make sure the chicken covers the sauce and the sauce isn't exposed or it'll burn) and spread the remaining marinade on the chicken. Roast for 35-45 minutes or until internal temp of the thickest part of chicken is at least 175 F.\r\nLet chicken rest for 5 minutes. Brush the chicken with some of the oil. Serve chicken with the sauce over steamed rice (or coconut rice).",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/020z181619788503.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=9ytR28QK6I8",
      "strIngredient1": "Chicken Thighs",
      "strIngredient2": "Challots",
      "strIngredient3": "Ginger",
      "strIngredient4": "Garlic Clove",
      "strIngredient5": "Cayenne Pepper",
      "strIngredient6": "Turmeric",
      "strIngredient7": "Cumin",
      "strIngredient8": "Coriander",
      "strIngredient9": "Fennel",
      "strIngredient10": "Tamarind Paste",
      "strIngredient11": "Coconut Milk",
      "strIngredient12": "Sugar",
      "strIngredient13": "Water",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "6",
      "strMeasure2": "16",
      "strMeasure3": "1 1/2 ",
      "strMeasure4": "6",
      "strMeasure5": "8",
      "strMeasure6": "2 tbs",
      "strMeasure7": "1 1/2 ",
      "strMeasure8": "1 1/2 ",
      "strMeasure9": "1 1/2 ",
      "strMeasure10": "2 tbs",
      "strMeasure11": "1 can ",
      "strMeasure12": "1 tsp ",
      "strMeasure13": "1 cup ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "http://www.curiousnut.com/roasted-spiced-chicken-ayam-percik/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52767",
      "strMeal": "Bakewell tart",
      "strDrinkAlternate": null,
      "strCategory": "Vegetarian",
      "strArea": "British",
      "strInstructions": "To make the pastry, measure the flour into a bowl and rub in the butter with your fingertips until the mixture resembles fine breadcrumbs. Add the water, mixing to form a soft dough.\r\nRoll out the dough on a lightly floured work surface and use to line a 20cm/8in flan tin. Leave in the fridge to chill for 30 minutes.\r\nPreheat the oven to 200C/400F/Gas 6 (180C fan).\r\nLine the pastry case with foil and fill with baking beans. Bake blind for about 15 minutes, then remove the beans and foil and cook for a further five minutes to dry out the base.\r\nFor the filing, spread the base of the flan generously with raspberry jam.\r\nMelt the butter in a pan, take off the heat and then stir in the sugar. Add ground almonds, egg and almond extract. Pour into the flan tin and sprinkle over the flaked almonds.\r\nBake for about 35 minutes. If the almonds seem to be browning too quickly, cover the tart loosely with foil to prevent them burning.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/wyrqqq1468233628.jpg",
      "strTags": "Tart,Baking,Alcoholic",
      "strYoutube": "https://www.youtube.com/watch?v=1ahpSTf_Pvk",
      "strIngredient1": "plain flour",
      "strIngredient2": "chilled butter",
      "strIngredient3": "cold water",
      "strIngredient4": "raspberry jam",
      "strIngredient5": "butter",
      "strIngredient6": "caster sugar",
      "strIngredient7": "ground almonds",
      "strIngredient8": "free-range egg, beaten",
      "strIngredient9": "almond extract",
      "strIngredient10": "flaked almonds",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": null,
      "strIngredient17": null,
      "strIngredient18": null,
      "strIngredient19": null,
      "strIngredient20": null,
      "strMeasure1": "175g/6oz",
      "strMeasure2": "75g/2½oz",
      "strMeasure3": "2-3 tbsp",
      "strMeasure4": "1 tbsp",
      "strMeasure5": "125g/4½oz",
      "strMeasure6": "125g/4½oz",
      "strMeasure7": "125g/4½oz",
      "strMeasure8": "1",
      "strMeasure9": "½ tsp",
      "strMeasure10": "50g/1¾oz",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": null,
      "strMeasure17": null,
      "strMeasure18": null,
      "strMeasure19": null,
      "strMeasure20": null,
      "strSource": null,
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52792",
      "strMeal": "Bread and Butter Pudding",
      "strDrinkAlternate": null,
      "strCategory": "Vegetarian",
      "strArea": "British",
      "strInstructions": "Grease a 1 litre/2 pint pie dish with butter.\r\nCut the crusts off the bread. Spread each slice with on one side with butter, then cut into triangles.\r\nArrange a layer of bread, buttered-side up, in the bottom of the dish, then add a layer of sultanas. Sprinkle with a little cinnamon, then repeat the layers of bread and sultanas, sprinkling with cinnamon, until you have used up all of the bread. Finish with a layer of bread, then set aside.\r\nGently warm the milk and cream in a pan over a low heat to scalding point. Don't let it boil.\r\nCrack the eggs into a bowl, add three quarters of the sugar and lightly whisk until pale.\r\nAdd the warm milk and cream mixture and stir well, then strain the custard into a bowl.\r\nPour the custard over the prepared bread layers and sprinkle with nutmeg and the remaining sugar and leave to stand for 30 minutes.\r\nPreheat the oven to 180C/355F/Gas 4.\r\nPlace the dish into the oven and bake for 30-40 minutes, or until the custard has set and the top is golden-brown.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/xqwwpy1483908697.jpg",
      "strTags": "Pudding,Brunch",
      "strYoutube": "https://www.youtube.com/watch?v=Vz5W1-BmOE4",
      "strIngredient1": "butter",
      "strIngredient2": "bread",
      "strIngredient3": "sultanas",
      "strIngredient4": "cinnamon",
      "strIngredient5": "milk",
      "strIngredient6": "double cream",
      "strIngredient7": "eggs",
      "strIngredient8": "sugar",
      "strIngredient9": "nutmeg",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "25g/1oz",
      "strMeasure2": "8 thin slices",
      "strMeasure3": "50g/2oz",
      "strMeasure4": "2 tsp",
      "strMeasure5": "350ml/12fl",
      "strMeasure6": "50ml/2fl oz",
      "strMeasure7": "2 free-range",
      "strMeasure8": "25g/1oz",
      "strMeasure9": "grated, to taste",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://cooking.nytimes.com/recipes/1018529-coq-au-vin",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52803",
      "strMeal": "Beef Wellington",
      "strDrinkAlternate": null,
      "strCategory": "Nonvegetarian",
      "strArea": "British",
      "strInstructions": "Put the mushrooms into a food processor with some seasoning and pulse to a rough paste. Scrape the paste into a pan and cook over a high heat for about 10 mins, tossing frequently, to cook out the moisture from the mushrooms. Spread out on a plate to cool.\r\nHeat in a frying pan and add a little olive oil. Season the beef and sear in the hot pan for 30 secs only on each side. (You don't want to cook it at this stage, just colour it). Remove the beef from the pan and leave to cool, then brush all over with the mustard.\r\nLay a sheet of cling film on a work surface and arrange the Parma ham slices on it, in slightly overlapping rows. With a palette knife, spread the mushroom paste over the ham, then place the seared beef fillet in the middle. Keeping a tight hold of the cling film from the edge, neatly roll the Parma ham and mushrooms around the beef to form a tight barrel shape. Twist the ends of the cling film to secure. Chill for 15-20 mins to allow the beef to set and keep its shape.\r\nRoll out the puff pastry on a floured surface to a large rectangle, the thickness of a £1 coin. Remove the cling film from the beef, then lay in the centre. Brush the surrounding pastry with egg yolk. Fold the ends over, the wrap the pastry around the beef, cutting off any excess.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/vvpprx1487325699.jpg",
      "strTags": "Meat,Stew",
      "strYoutube": "https://www.youtube.com/watch?v=FS8u1RBdf6I",
      "strIngredient1": "mushrooms",
      "strIngredient2": "English Mustard",
      "strIngredient3": "Olive Oil",
      "strIngredient4": "Beef Fillet",
      "strIngredient5": "Parma ham",
      "strIngredient6": "Puff Pastry",
      "strIngredient7": "Flour",
      "strIngredient8": "Egg Yolks",
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient16": null,
      "strIngredient17": null,
      "strIngredient18": null,
      "strIngredient19": null,
      "strIngredient20": null,
      "strMeasure1": "400g",
      "strMeasure2": "1-2tbsp",
      "strMeasure3": "Dash",
      "strMeasure4": "750g piece",
      "strMeasure5": "6-8 slices",
      "strMeasure6": "500g",
      "strMeasure7": "Dusting",
      "strMeasure8": "2 Beaten ",
      "strMeasure9": "",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "http://www.goodtoknow.co.uk/recipes/164868/Gordon-Ramsay-s-beef-Wellington",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52807",
      "strMeal": "Baingan Bharta",
      "strDrinkAlternate": null,
      "strCategory": "Vegetarian",
      "strArea": "Indian",
      "strInstructions": "Rinse the baingan (eggplant or aubergine) in water. Pat dry with a kitchen napkin. Apply some oil all over and\r\nkeep it for roasting on an open flame. You can also grill the baingan or roast in the oven. But then you won't get\r\nthe smoky flavor of the baingan. Keep the eggplant turning after a 2 to 3 minutes on the flame, so that its evenly\r\ncooked. You could also embed some garlic cloves in the baingan and then roast it.\r\n2. Roast the aubergine till its completely cooked and tender. With a knife check the doneness. The knife should slid\r\neasily in aubergines without any resistance. Remove the baingan and immerse in a bowl of water till it cools\r\ndown.\r\n3. You can also do the dhungar technique of infusing charcoal smoky flavor in the baingan. This is an optional step.\r\nUse natural charcoal for this method. Heat a small piece of charcoal on flame till it becomes smoking hot and red.\r\n4. Make small cuts on the baingan with a knife. Place the red hot charcoal in the same plate where the roasted\r\naubergine is kept. Add a few drops of oil on the charcoal. The charcoal would begin to smoke.\r\n5. As soon as smoke begins to release from the charcoal, cover the entire plate tightly with a large bowl. Allow the\r\ncharcoal smoke to get infused for 1 to 2 minutes. The more you do, the more smoky the baingan bharta will\r\nbecome. I just keep for a minute. Alternatively, you can also do this dhungar method once the baingan bharta is\r\ncooked, just like the way we do for Dal Tadka.\r\n6. Peel the skin from the roasted and smoked eggplant.\r\n7. Chop the cooked eggplant finely or you can even mash it.\r\n8. In a kadai or pan, heat oil. Then add finely chopped onions and garlic.\r\n9. Saute the onions till translucent. Don't brown them.\r\n10.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/urtpqw1487341253.jpg",
      "strTags": "Spicy,Bun,Calorific",
      "strYoutube": "https://www.youtube.com/watch?v=-84Zz2EP4h4",
      "strIngredient1": "Aubergine",
      "strIngredient2": "Onion",
      "strIngredient3": "Tomatoes",
      "strIngredient4": "Garlic",
      "strIngredient5": "Green Chili",
      "strIngredient6": "Red Chili Powder",
      "strIngredient7": "Oil",
      "strIngredient8": "Coriander Leaves",
      "strIngredient9": "salt",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "1 large",
      "strMeasure2": "½ cup ",
      "strMeasure3": "1 cup",
      "strMeasure4": "6 cloves",
      "strMeasure5": "1",
      "strMeasure6": "¼ teaspoon",
      "strMeasure7": "1.5 tablespoon",
      "strMeasure8": "1 tablespoon chopped",
      "strMeasure9": "as required",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "http://www.vegrecipesofindia.com/baingan-bharta-recipe-punjabi-baingan-bharta-recipe/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
   
    {
      "idMeal": "52824",
      "strMeal": "Beef Sunday Roast",
      "strDrinkAlternate": null,
      "strCategory": "Nonvegetrian",
      "strArea": "British",
      "strInstructions": "Cook the Broccoli and Carrots in a pan of boiling water until tender.\r\n\r\nRoast the Beef and Potatoes in the oven for 45mins, the potatoes may need to be checked regularly to not overcook.\r\n\r\nTo make the Yorkshire puddings:\r\nHeat oven to 230C/fan 210C/gas 8. Drizzle a little sunflower oil evenly into 2 x 4-hole Yorkshire pudding tins or a 12-hole non-stick muffin tin and place in the oven to heat through\r\nTo make the batter, tip 140g plain flour into a bowl and beat in four eggs until smooth. Gradually add 200ml milk and carry on beating until the mix is completely lump-free. Season with salt and pepper. Pour the batter into a jug, then remove the hot tins from the oven. Carefully and evenly pour the batter into the holes. Place the tins back in the oven and leave undisturbed for 20-25 mins until the puddings have puffed up and browned. Serve immediately.\r\n\r\nPlate up and add the Gravy as desired.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/ssrrrs1503664277.jpg",
      "strTags": "MainMeal",
      "strYoutube": "https://www.youtube.com/watch?v=2l3-dBdNehY",
      "strIngredient1": "Beef",
      "strIngredient2": "Broccoli",
      "strIngredient3": "Potatoes",
      "strIngredient4": "Carrots",
      "strIngredient5": "plain flour",
      "strIngredient6": "Eggs",
      "strIngredient7": "milk",
      "strIngredient8": "sunflower oil",
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient16": null,
      "strIngredient17": null,
      "strIngredient18": null,
      "strIngredient19": null,
      "strIngredient20": null,
      "strMeasure1": "8 slices",
      "strMeasure2": "12 florets",
      "strMeasure3": "1 Packet",
      "strMeasure4": "1 Packet",
      "strMeasure5": "140g",
      "strMeasure6": "4",
      "strMeasure7": "200ml",
      "strMeasure8": "drizzle (for cooking)",
      "strMeasure9": "",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://www.bbcgoodfood.com/recipes/9020/best-yorkshire-puddings",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52826",
      "strMeal": "Braised Beef Chilli",
      "strDrinkAlternate": null,
      "strCategory": "Nonvegetarian",
      "strArea": "Mexican",
      "strInstructions": "Preheat the oven to 120C/225F/gas mark 1.\r\n\r\nTake the meat out of the fridge to de-chill. Pulse the onions and garlic in a food processor until finely chopped. Heat 2 tbsp olive oil in a large casserole and sear the meat on all sides until golden.\r\n\r\nSet to one side and add another small slug of oil to brown the chorizo. Remove and add the onion and garlic, spices, herbs and chillies then cook until soft in the chorizo oil. Season with salt and pepper and add the vinegar, tomatoes, ketchup and sugar.\r\n\r\nPut all the meat back into the pot with 400ml water (or red wine if you prefer), bring up to a simmer and cook, covered, in the low oven.\r\n\r\nAfter 2 hours, check the meat and add the beans. Cook for a further hour and just before serving, pull the meat apart with a pair of forks.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/uuqvwu1504629254.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=z4kSoJgsu6Y",
      "strIngredient1": "Beef",
      "strIngredient2": "Onions",
      "strIngredient3": "Garlic",
      "strIngredient4": "Olive oil",
      "strIngredient5": "Chorizo",
      "strIngredient6": "Cumin",
      "strIngredient7": "All spice",
      "strIngredient8": "Cloves",
      "strIngredient9": "Cinnamon stick",
      "strIngredient10": "Bay Leaves",
      "strIngredient11": "Oregano",
      "strIngredient12": "Ancho Chillies",
      "strIngredient13": "Balsamic Vinegar",
      "strIngredient14": "Plum Tomatoes",
      "strIngredient15": "Tomato Ketchup",
      "strIngredient16": "Dark Brown Sugar",
      "strIngredient17": "Borlotti Beans",
      "strIngredient18": null,
      "strIngredient19": null,
      "strIngredient20": null,
      "strMeasure1": "1kg",
      "strMeasure2": "3",
      "strMeasure3": "4 cloves",
      "strMeasure4": "Dash",
      "strMeasure5": "300g",
      "strMeasure6": "2 tsp",
      "strMeasure7": "2 tsp",
      "strMeasure8": "1 tsp",
      "strMeasure9": "1 large",
      "strMeasure10": "3",
      "strMeasure11": "2 tsp dried",
      "strMeasure12": "2 ancho",
      "strMeasure13": "3 tbsp",
      "strMeasure14": "2 x 400g",
      "strMeasure15": "2 tbsp",
      "strMeasure16": "2 tbsp",
      "strMeasure17": "2 x 400g tins",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "http://www.telegraph.co.uk/food-and-drink/recipes/braised-beef-chilli-con-carne/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52834",
      "strMeal": "Beef stroganoff",
      "strDrinkAlternate": null,
      "strCategory": "Nonvegetatian",
      "strArea": "Russian",
      "strInstructions": "Heat the olive oil in a non-stick frying pan then add the sliced onion and cook on a medium heat until completely softened, so around 15 mins, adding a little splash of water if they start to stick at all. Crush in the garlic and cook for a 2-3 mins further, then add the butter. Once the butter is foaming a little, add the mushrooms and cook for around 5 mins until completely softened. Season everything well, then tip onto a plate.\r\nTip the flour into a bowl with a big pinch of salt and pepper, then toss the steak in the seasoned flour. Add the steak pieces to the pan, splashing in a little oil if the pan looks particularly dry, and fry for 3-4 mins, until well coloured. Tip the onions and mushrooms back into the pan. Whisk the crème fraîche, mustard and beef stock together, then pour into the pan. Cook over a medium heat for around 5 mins. Scatter with parsley, then serve with pappardelle or rice.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/svprys1511176755.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=PQHgQX1Ss74",
      "strIngredient1": "Olive Oil",
      "strIngredient2": "Onions",
      "strIngredient3": "Garlic",
      "strIngredient4": "Butter",
      "strIngredient5": "Mushrooms",
      "strIngredient6": "Beef Fillet",
      "strIngredient7": "Plain Flour",
      "strIngredient8": "Creme Fraiche",
      "strIngredient9": "English Mustard",
      "strIngredient10": "Beef Stock",
      "strIngredient11": "Parsley",
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient16": null,
      "strIngredient17": null,
      "strIngredient18": null,
      "strIngredient19": null,
      "strIngredient20": null,
      "strMeasure1": "1 tbls",
      "strMeasure2": "1",
      "strMeasure3": "1 clove",
      "strMeasure4": "1 tbsp",
      "strMeasure5": "250g",
      "strMeasure6": "500g",
      "strMeasure7": "1tbsp",
      "strMeasure8": "150g",
      "strMeasure9": "1 tbsp",
      "strMeasure10": "100ml",
      "strMeasure11": "Topping",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://www.bbcgoodfood.com/recipes/beef-stroganoff",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52842",
      "strMeal": "Broccoli & Stilton soup",
      "strDrinkAlternate": null,
      "strCategory": "Vegetarian",
      "strArea": "British",
      "strInstructions": "Heat the rapeseed oil in a large saucepan and then add the onions. Cook on a medium heat until soft. Add a splash of water if the onions start to catch.\r\n\r\nAdd the celery, leek, potato and a knob of butter. Stir until melted, then cover with a lid. Allow to sweat for 5 minutes. Remove the lid.\r\n\r\nPour in the stock and add any chunky bits of broccoli stalk. Cook for 10 – 15 minutes until all the vegetables are soft.\r\n\r\nAdd the rest of the broccoli and cook for a further 5 minutes. Carefully transfer to a blender and blitz until smooth. Stir in the stilton, allowing a few lumps to remain. Season with black pepper and serve.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/tvvxpv1511191952.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=_HgVLpmNxTY",
      "strIngredient1": "Rapeseed Oil",
      "strIngredient2": "Onion",
      "strIngredient3": "Celery",
      "strIngredient4": "Leek",
      "strIngredient5": "Potatoes",
      "strIngredient6": "Butter",
      "strIngredient7": "Vegetable Stock",
      "strIngredient8": "Broccoli",
      "strIngredient9": "Stilton Cheese",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2 tblsp ",
      "strMeasure2": "1 finely chopped ",
      "strMeasure3": "1",
      "strMeasure4": "1 sliced",
      "strMeasure5": "1 medium",
      "strMeasure6": "1 knob",
      "strMeasure7": "1 litre hot",
      "strMeasure8": "1 Head chopped",
      "strMeasure9": "140g",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://www.bbcgoodfood.com/recipes/1940679/broccoli-and-stilton-soup",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    
  
  ]
export default food;